# SITE CONFIGURATION
title: Ledger Blog # your site title
author: CharlesLedger
description: > # Meta description of Homepage
   The latest news about technology and engineering at Ledger.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://blog.ledger.com/"

# SEO PLUGIN
social:
  name: Ledger Blog
  links:
    - https://twitter.com/ledger
    - https://github.com/ledgerHQ

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Engineering', link: '/'}
  - {name: 'Financial Solutions', link: '/financial-solutions/'}
  - {name: 'About', link: '/about'}

tagline: >
   Technology and Engineering at Ledger

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: engineering@ledger.fr # email for form submission

twitter_username: ledger
github_username:  ledgerHQ


# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
